  export const shopItems = [
    { 
      id: 1, 
      title: "2 - Storey 2 Room House Plan - ID", 
      price: "Tshs 151.20", 
      image: "/03.jpg",
      floors: "2",
      bedroom: "4",
      bathroom: "2",
      height: "30",
      width: "10",
      area: "170"
    },
    { 
      id: 2, 
      title: "3 - Storey 3 Room House Plan - ID", 
      price: "Tshs 189.50", 
      image: "/path-to-image-2.jpg", 
      floors: "2",
      bedroom: "2",
      bathroom: "1",
      height: "30",
      width: "90",
      area: "900"
    },
    { 
      id: 3, 
      title: "Modern Villa Design - ID", 
      price: "Tshs 210.75", 
      image: "/path-to-image-3.jpg", 
      floors: "2",
      bedroom: "4",
      bathroom: "2",
      height: "30",
      width: "10",
      area: "170"
    },
    { 
      id: 4, 
      title: "Single Story Cottage - ID", 
      price: "Tshs 125.30", 
      image: "/path-to-image-4.jpg", 
      floors: "2",
      bedroom: "4",
      bathroom: "2",
      height: "30",
      width: "10",
      area: "170"
    },
    {
       id: 5, 
       title: "Single Story Cottage - ID", 
       price: "Tshs 125.30", 
       image: "/path-to-image-4.jpg", 
       floors: "2",
        bedroom: "4",
        bathroom: "2",
        height: "30",
        width: "10",
        area: "170"
    },
    {
       id: 6, 
       title: "Single Story Cottage - ID", 
       price: "Tshs 125.30", 
       image: "/path-to-image-4.jpg", 
       floors: "2",
      bedroom: "4",
      bathroom: "2",
      height: "30",
      width: "10",
      area: "170"
    },
    {
       id: 7, 
       title: "Single Story Cottage - ID", 
       price: "Tshs 125.30", 
       image: "/path-to-image-4.jpg", 
      floors: "2",
      bedroom: "4",
      bathroom: "2",
      height: "30",
      width: "10",
      area: "170"
    },
    { 
      id: 8, 
      title: "Single Story Cottage - ID", 
      price: "Tshs 125.30", 
      image: "/path-to-image-4.jpg",
      floors: "2",
      bedroom: "4",
      bathroom: "2",
      height: "30",
      width: "10",
      area: "170"
    },
    {
       id: 9, 
       title: "Single Story Cottage - ID", 
       price: "Tshs 125.30", 
       image: "/path-to-image-4.jpg", 
       floors: "2",
      bedroom: "4",
      bathroom: "2",
      height: "30",
      width: "20",
      area: "870"
    },
    {
       id: 10, 
       title: "Single Story Cottage - ID", 
       price: "Tshs 125.30", 
       image: "/path-to-image-4.jpg", 
       floors: "2",
      bedroom: "4",
      bathroom: "2",
      height: "17",
      width: "9",
      area: "230"
    },
    {
       id: 11, 
       title: "Single Story Cottage - ID", 
       price: "Tshs 125.30", 
       image: "/path-to-image-4.jpg", 
       floors: "20",
      bedroom: "4",
      bathroom: "2",
      height: "30",
      width: "17",
      area: "160"
    },
  ];