import { Nunito } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/component/01/toastprovider";
import { Providers } from "./providers";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "Jenganasi",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${nunito.variable} antialiased`}>
        <Providers>
            <ToastProvider>{children}</ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
export default RootLayout;
